############# English navigation ##############

# main menu
[[main]]
name = "GC Cloud One: Aurora"
url = "/"
weight = 1
identifier = "home"
  [main.params]
  slot = "home"

[[main]]
name = "Platform"
url = "/platform"
weight = 5

  [[main]]
  name = "Proposal"
  parent = "Platform"
  url = "/proposal"
  weight = 3

  [[main]]
  name = "Roadmap"
  parent = "Platform"
  url = "/roadmap"
  weight = 5

  [[main]]
  name = "Vision"
  parent = "Platform"
  url = "/vision"
  weight = 7

  [[main]]
  name = "Architecture"
  parent = "Platform"
  url = "/architecture"
  weight = 9

[[main]]
name = "User Guides"
url = "/user-guides"
weight = 10

  [[main]]
  name = "Onboarding"
  parent = "User Guides"
  url = "/user-guides/onboarding"
  weight = 1

[[main]]
name = "Team"
url = "/team"
weight = 15

  [[main]]
  name = "Standard Operating Procedures"
  parent = "Team"
  url = "/team/sop"
  weight = 1

  [[main]]
  name = "Monitoring"
  parent = "Team"
  url = "/team/monitoring-alerts/"
  weight = 2

  [[main]]
  name = "Appendix"
  parent = "Team"
  url = "/team/appendix"
  weight = 3

[[main]]
name = "Community"
url = "/community"
weight = 20

  [[main]]
  name = "Get involved"
  parent = "Community"
  url = "/get-involved"
  weight = 1

  [[main]]
  name = "Rules of Engagement"
  parent = "Community"
  url = "/rules-of-engagement"
  weight = 1

  [[main]]
  name = "Technical Advisory Group"
  parent = "Community"
  url = "/technical-advisory-group"
  weight = 1

[[breadcrumb]]
name = "GC Cloud One"
url = "https://hosting-services-hebergement.canada.ca/s/gc-cloud-one?language=en_US"
weight = 1

[[contextual]]
name = "Contact us"
url = "/contact"
weight = 10

[[contextual]]
name = "Report an issue"
url = "https://github.com/gccloudone/aurora/issues/new/choose"
weight = 20

[[contextual]]
name = "About us"
url = "/about"
weight = 30
