############# English navigation ##############

# main menu
[[main]]
name = "GC Cloud One: Aurora"
url = "/"
weight = 1
identifier = "home"

[[main]]
name = "Platform"
url = "/platform"
weight = 5

  [[main]]
  name = "Proposal"
  parent = "Platform"
  url = "/proposal"
  weight = 1

  [[main]]
  name = "Components"
  parent = "Platform"
  url = "/components"
  weight = 5

[[main]]
name = "Community"
url = "/community"
weight = 10

  [[main]]
  name = "Get involved"
  parent = "Community"
  url = "/get-involved"
  weight = 1

  [[main]]
  name = "Rules of Engagement"
  parent = "Community"
  url = "/rules-of-engagement"
  weight = 1

[[main]]
name = "Contact us"
url = "/contact"
weight = 15

[[breadcrumb]]
name = "GC Cloud One"
url = "https://gccloudone.ca"
weight = 1
