############# English navigation ##############

# main menu
[[main]]
name = "GC Cloud One: Aurora"
url = "/"
weight = 1
identifier = "home"

[[main]]
name = "Platform"
url = "/platform"
weight = 5

  [[main]]
  name = "Proposal"
  parent = "Platform"
  url = "/proposal"
  weight = 1

  [[main]]
  name = "Vision"
  parent = "Platform"
  url = "/vision"
  weight = 3

  [[main]]
  name = "Architecture"
  parent = "Platform"
  url = "/architecture"
  weight = 5

[[main]]
name = "Team"
url = "/team"
weight = 10

  [[main]]
  name = "Standard Operating Procedures"
  parent = "Team"
  url = "/team/sop"
  weight = 1

[[main]]
name = "Community"
url = "/community"
weight = 15

  [[main]]
  name = "Get involved"
  parent = "Community"
  url = "/get-involved"
  weight = 1

  [[main]]
  name = "Rules of Engagement"
  parent = "Community"
  url = "/rules-of-engagement"
  weight = 1

  [[main]]
  name = "Technical Advisory Group"
  parent = "Community"
  url = "/technical-advisory-group"
  weight = 1

[[main]]
name = "Contact us"
url = "/contact"
weight = 20

[[breadcrumb]]
name = "GC Cloud One"
url = "https://gccloudone.ca"
weight = 1
